services:
  kv1:
    build: ..
    container_name: kv1
    command: ["--id=kv1","--addr=:8080","--advertise=http://kv1:8080","--peers=http://kv2:8080,http://kv3:8080","--data=/data"]
    ports: ["8081:8080"]
    networks: [kvnet]
    volumes:
      - kv1data:/data
  kv2:
    build: ..
    container_name: kv2
    command: ["--id=kv2","--addr=:8080","--advertise=http://kv2:8080","--peers=http://kv1:8080,http://kv3:8080","--data=/data"]
    ports: ["8082:8080"]
    networks: [kvnet]
    volumes:
      - kv2data:/data
  kv3:
    build: ..
    container_name: kv3
    command: ["--id=kv3","--addr=:8080","--advertise=http://kv3:8080","--peers=http://kv1:8080,http://kv2:8080","--data=/data"]
    ports: ["8083:8080"]
    networks: [kvnet]
    volumes:
      - kv3data:/data

networks:
  kvnet:

volumes:
  kv1data:
  kv2data:
  kv3data:
